[env]
CC_x86_64-unknown-linux-musl = "gcc"

[build]
#rustflags = ["--cfg", "tokio_unstable"]
#target = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]

[target.x86_64-unknown-linux-musl]
#linker = "rust-lld"

[target.aarch64-linux-android]
linker = "aarch64-linux-android33-clang"

[target.x86_64-pc-windows-msvc]
#linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[target.arm-unknown-linux-musleabi]
linker = "rust-lld"

#fn main() {
#println!("cargo:rerun-if-changed=build.rs");
#println!("cargo:rerun-if-changed=dynamiclist");
#
#}
